In [1]:
import pandas as pd
import numpy as np
from glob import glob
from medpy.io import load
import os

In [2]:
datadir = '../input/Training/*'
GT_list = sorted(glob(os.path.join(datadir, 'GT01.nii*')))

In [3]:
#density
density = np.zeros(len(GT_list))
number = np.zeros(len(GT_list))
label = np.array([])
for idx, gt in enumerate(GT_list):
    test = load(gt)[0]
    label = np.concatenate( (label, np.unique(np.array(test))), axis=0 )
    density[idx] = np.mean(test).astype(np.float32)
    number[idx] = np.sum(test).astype(np.float32)

In [4]:
info = pd.read_csv('../input/info.csv', nrows=30)
info = info.sort_values(['ID'])
info.head(10)

             ID  mRS TICI  TSS    TTT
0    training_1    1   2b  160   85.0
8   training_10    1    3  128   90.0
9   training_11    1    0  129  221.0
10  training_12    1    3  157  124.0
11  training_13    2   2b  175   86.0
12  training_14    2    3  135  119.0
13  training_15    0   2b  249  131.0
14  training_16    1   2b  120  104.0
15  training_18    4    1  181   84.0
16  training_19    0   2a  281   81.0

In [5]:
info['GT']= density
info = info.fillna(np.mean(info.TTT))
info['TIME']= info.TSS+info.TTT
print(info)

             ID  mRS TICI  TSS         TTT        GT        TIME
0    training_1    1   2b  160   85.000000  0.000301  245.000000
8   training_10    1    3  128   90.000000  0.000474  218.000000
9   training_11    1    0  129  221.000000  0.001506  350.000000
10  training_12    1    3  157  124.000000  0.000841  281.000000
11  training_13    2   2b  175   86.000000  0.007537  261.000000
12  training_14    2    3  135  119.000000  0.015234  254.000000
13  training_15    0   2b  249  131.000000  0.000303  380.000000
14  training_16    1   2b  120  104.000000  0.003616  224.000000
15  training_18    4    1  181   84.000000  0.030536  265.000000
16  training_19    0   2a  281   81.000000  0.000807  362.000000
1    training_2    1   2b  105  150.000000  0.000069  255.000000
17  training_20    1    1  196  116.000000  0.002231  312.000000
18  training_21    1   2a  245  115.000000  0.000820  360.000000
19  training_22    3    0  138  142.000000  0.010316  280.000000
20  training_23    1    0   92  133.000000  0.001761  225.000000
21  training_24    2    0  108   71.000000  0.013549  179.000000
22  training_26    2   2a  295   95.000000  0.005910  390.000000
23  training_27    3    1   80   79.000000  0.012331  159.000000
24  training_28    1   2b  162  108.925926  0.000644  270.925926
25  training_30    3    3   61  108.925926  0.001900  169.925926
26  training_31    3   2b  296   93.000000  0.004608  389.000000
27  training_32    2   2b   65   80.000000  0.009222  145.000000
28  training_33    3    0  132  108.925926  0.004163  240.925926
29  training_35    2    3   92   69.000000  0.000657  161.000000
2    training_4    4    3  116   93.000000  0.031039  209.000000
3    training_5    2    3   81  162.000000  0.007394  243.000000
4    training_6    1   2b  121   92.000000  0.000285  213.000000
5    training_7    2   2b  141   99.000000  0.015313  240.000000
6    training_8    1   2b  308  142.000000  0.002775  450.000000
7    training_9    1    3   90   85.000000  0.000825  175.000000

In [6]:
info.sort_values(['GT'])

             ID  mRS TICI  TSS         TTT        GT        TIME
1    training_2    1   2b  105  150.000000  0.000069  255.000000
4    training_6    1   2b  121   92.000000  0.000285  213.000000
0    training_1    1   2b  160   85.000000  0.000301  245.000000
13  training_15    0   2b  249  131.000000  0.000303  380.000000
8   training_10    1    3  128   90.000000  0.000474  218.000000
24  training_28    1   2b  162  108.925926  0.000644  270.925926
29  training_35    2    3   92   69.000000  0.000657  161.000000
16  training_19    0   2a  281   81.000000  0.000807  362.000000
18  training_21    1   2a  245  115.000000  0.000820  360.000000
7    training_9    1    3   90   85.000000  0.000825  175.000000
10  training_12    1    3  157  124.000000  0.000841  281.000000
9   training_11    1    0  129  221.000000  0.001506  350.000000
20  training_23    1    0   92  133.000000  0.001761  225.000000
25  training_30    3    3   61  108.925926  0.001900  169.925926
17  training_20    1    1  196  116.000000  0.002231  312.000000
6    training_8    1   2b  308  142.000000  0.002775  450.000000
14  training_16    1   2b  120  104.000000  0.003616  224.000000
28  training_33    3    0  132  108.925926  0.004163  240.925926
26  training_31    3   2b  296   93.000000  0.004608  389.000000
22  training_26    2   2a  295   95.000000  0.005910  390.000000
3    training_5    2    3   81  162.000000  0.007394  243.000000
11  training_13    2   2b  175   86.000000  0.007537  261.000000
27  training_32    2   2b   65   80.000000  0.009222  145.000000
19  training_22    3    0  138  142.000000  0.010316  280.000000
23  training_27    3    1   80   79.000000  0.012331  159.000000
21  training_24    2    0  108   71.000000  0.013549  179.000000
12  training_14    2    3  135  119.000000  0.015234  254.000000
5    training_7    2   2b  141   99.000000  0.015313  240.000000
15  training_18    4    1  181   84.000000  0.030536  265.000000
2    training_4    4    3  116   93.000000  0.031039  209.000000

In [7]:
info.mRS.value_counts()

1    13
2     8
3     5
4     2
0     2
Name: mRS, dtype: int64

In [8]:
info_dummy = pd.get_dummies(info, columns=['TICI'])
info_dummy

,ID,mRS,TSS,TTT,GT,TIME,TICI_0,TICI_1,TICI_2a,TICI_2b,TICI_3
0,training_1,1,160,85.000000,0.000301,245.000000,0.0,0.0,0.0,1.0,0.0
8,training_10,1,128,90.000000,0.000474,218.000000,0.0,0.0,0.0,0.0,1.0
9,training_11,1,129,221.000000,0.001506,350.000000,1.0,0.0,0.0,0.0,0.0
10,training_12,1,157,124.000000,0.000841,281.000000,0.0,0.0,0.0,0.0,1.0
11,training_13,2,175,86.000000,0.007537,261.000000,0.0,0.0,0.0,1.0,0.0
12,training_14,2,135,119.000000,0.015234,254.000000,0.0,0.0,0.0,0.0,1.0
13,training_15,0,249,131.000000,0.000303,380.000000,0.0,0.0,0.0,1.0,0.0
14,training_16,1,120,104.000000,0.003616,224.000000,0.0,0.0,0.0,1.0,0.0
15,training_18,4,181,84.000000,0.030536,265.000000,0.0,1.0,0.0,0.0,0.0
16,training_19,0,281,81.000000,0.000807,362.000000,0.0,0.0,1.0,0.0,0.0
1,training_2,1,105,150.000000,0.000069,255.000000,0.0,0.0,0.0,1.0,0.0
17,training_20,1,196,116.000000,0.002231,312.000000,0.0,1.0,0.0,0.0,0.0
18,training_21,1,245,115.000000,0.000820,360.000000,0.0,0.0,1.0,0.0,0.0
19,training_22,3,138,142.000000,0.010316,280.000000,1.0,0.0,0.0,0.0,0.0
20,training_23,1,92,133.000000,0.001761,225.000000,1.0,0.0,0.0,0.0,0.0
21,training_24,2,108,71.000000,0.013549,179.000000,1.0,0.0,0.0,0.0,0.0
22,training_26,2,295,95.000000,0.005910,390.000000,0.0,0.0,1.0,0.0,0.0
23,training_27,3,80,79.000000,0.012331,159.000000,0.0,1.0,0.0,0.0,0.0
24,training_28,1,162,108.925926,0.000644,270.925926,0.0,0.0,0.0,1.0,0.0
25,training_30,3,61,108.925926,0.001900,169.925926,0.0,0.0,0.0,0.0,1.0
26,training_31,3,296,93.000000,0.004608,389.000000,0.0,0.0,0.0,1.0,0.0
27,training_32,2,65,80.000000,0.009222,145.000000,0.0,0.0,0.0,1.0,0.0
28,training_33,3,132,108.925926,0.004163,240.925926,1.0,0.0,0.0,0.0,0.0
29,training_35,2,92,69.000000,0.000657,161.000000,0.0,0.0,0.0,0.0,1.0
2,training_4,4,116,93.000000,0.031039,209.000000,0.0,0.0,0.0,0.0,1.0
3,training_5,2,81,162.000000,0.007394,243.000000,0.0,0.0,0.0,0.0,1.0
4,training_6,1,121,92.000000,0.000285,213.000000,0.0,0.0,0.0,1.0,0.0
5,training_7,2,141,99.000000,0.015313,240.000000,0.0,0.0,0.0,1.0,0.0
6,training_8,1,308,142.000000,0.002775,450.000000,0.0,0.0,0.0,1.0,0.0
7,training_9,1,90,85.000000,0.000825,175.000000,0.0,0.0,0.0,0.0,1.0

In [9]:
train_y = info_dummy.mRS
train_X = info_dummy.drop(['ID','mRS','GT'], axis=1)

In [14]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(train_X[['TSS','TTT','TIME']])
df_normalized = pd.DataFrame(x_scaled)
train_X[['TSS','TTT','TIME']]= df_normalized

           0         1         2
0   0.400810  0.105263  0.327869
1   0.271255  0.138158  0.239344
2   0.275304  1.000000  0.672131
3   0.388664  0.361842  0.445902
4   0.461538  0.111842  0.380328
5   0.299595  0.328947  0.357377
6   0.761134  0.407895  0.770492
7   0.238866  0.230263  0.259016
8   0.485830  0.098684  0.393443
9   0.890688  0.078947  0.711475
10  0.178138  0.532895  0.360656
11  0.546559  0.309211  0.547541
12  0.744939  0.302632  0.704918
13  0.311741  0.480263  0.442623
14  0.125506  0.421053  0.262295
15  0.190283  0.013158  0.111475
16  0.947368  0.171053  0.803279
17  0.076923  0.065789  0.045902
18  0.408907  0.262671  0.412872
19  0.000000  0.262671  0.081724
20  0.951417  0.157895  0.800000
21  0.016194  0.072368  0.000000
22  0.287449  0.262671  0.314511
23  0.125506  0.000000  0.052459
24  0.222672  0.157895  0.209836
25  0.080972  0.611842  0.321311
26  0.242915  0.151316  0.222951
27  0.323887  0.197368  0.311475
28  1.000000  0.480263  1.000000
29  0.117409  0.105263  0.098361

In [20]:
train_X.index = range(30)
train_y.index = range(30)
train_X

         TSS       TTT      TIME  TICI_0  TICI_1  TICI_2a  TICI_2b  TICI_3
0   0.400810  0.105263  0.327869     0.0     0.0      0.0      1.0     0.0
1   0.485830  0.098684  0.393443     0.0     0.0      0.0      0.0     1.0
2   0.890688  0.078947  0.711475     1.0     0.0      0.0      0.0     0.0
3   0.178138  0.532895  0.360656     0.0     0.0      0.0      0.0     1.0
4   0.546559  0.309211  0.547541     0.0     0.0      0.0      1.0     0.0
5   0.744939  0.302632  0.704918     0.0     0.0      0.0      0.0     1.0
6   0.311741  0.480263  0.442623     0.0     0.0      0.0      1.0     0.0
7   0.125506  0.421053  0.262295     0.0     0.0      0.0      1.0     0.0
8   0.190283  0.013158  0.111475     0.0     1.0      0.0      0.0     0.0
9   0.947368  0.171053  0.803279     0.0     0.0      1.0      0.0     0.0
10  0.271255  0.138158  0.239344     0.0     0.0      0.0      1.0     0.0
11  0.076923  0.065789  0.045902     0.0     1.0      0.0      0.0     0.0
12  0.408907  0.262671  0.412872     0.0     0.0      1.0      0.0     0.0
13  0.000000  0.262671  0.081724     1.0     0.0      0.0      0.0     0.0
14  0.951417  0.157895  0.800000     1.0     0.0      0.0      0.0     0.0
15  0.016194  0.072368  0.000000     1.0     0.0      0.0      0.0     0.0
16  0.287449  0.262671  0.314511     0.0     0.0      1.0      0.0     0.0
17  0.125506  0.000000  0.052459     0.0     1.0      0.0      0.0     0.0
18  0.222672  0.157895  0.209836     0.0     0.0      0.0      1.0     0.0
19  0.080972  0.611842  0.321311     0.0     0.0      0.0      0.0     1.0
20  0.242915  0.151316  0.222951     0.0     0.0      0.0      1.0     0.0
21  0.323887  0.197368  0.311475     0.0     0.0      0.0      1.0     0.0
22  1.000000  0.480263  1.000000     1.0     0.0      0.0      0.0     0.0
23  0.117409  0.105263  0.098361     0.0     0.0      0.0      0.0     1.0
24  0.275304  1.000000  0.672131     0.0     0.0      0.0      0.0     1.0
25  0.388664  0.361842  0.445902     0.0     0.0      0.0      0.0     1.0
26  0.461538  0.111842  0.380328     0.0     0.0      0.0      1.0     0.0
27  0.299595  0.328947  0.357377     0.0     0.0      0.0      1.0     0.0
28  0.761134  0.407895  0.770492     0.0     0.0      0.0      1.0     0.0
29  0.238866  0.230263  0.259016     0.0     0.0      0.0      0.0     1.0

In [52]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

In [55]:
C_list = np.logspace(-1.0, 10.0, num=12)
for c in C_list:
    print(np.mean(LogisticRegression(C = c).fit(train_X, train_y).predict(train_X) == train_y))

0.433333333333
0.466666666667
0.433333333333
0.5
0.5
0.533333333333
0.533333333333
0.533333333333
0.533333333333
0.533333333333
0.533333333333
0.533333333333

In [57]:
fit = LogisticRegression(C = (10**4)).fit(train_X, train_y)

In [63]:
test_info = pd.read_csv('../input/20160915_ISLES2016_Testing.csv')
test_info['TIME'] = test_info.TSS + test_info.TTT
test_info = pd.get_dummies(test_info, columns=['TICI'])

In [64]:
x_scaled = min_max_scaler.fit_transform(test_info[['TSS','TTT','TIME']])
df_normalized = pd.DataFrame(x_scaled)
test_info[['TSS','TTT','TIME']]= df_normalized

In [67]:
test_X = test_info.drop(['ID','mRS'], axis=1)

In [69]:
fit.predict(test_X)

array([2, 1, 4, 2, 2, 1, 0, 2, 3, 2, 2, 1, 4, 3, 4, 2, 2, 2, 0])

In [70]:
test_submit = pd.read_csv('../input/20160915_ISLES2016_Testing.csv')
test_submit.mRS = fit.predict(test_X)

In [72]:
test_submit.to_csv('../input/isles2016_task2.csv', index=False)